DROP TABLE IF EXISTS note;
DROP TABLE IF EXISTS additional_content;
DROP TABLE IF EXISTS person_publication;
DROP TABLE IF EXISTS crossref;
DROP TABLE IF EXISTS citation;
DROP TABLE IF EXISTS publication;
DROP TABLE IF EXISTS namealias;
DROP TABLE IF EXISTS person;

DROP TYPE IF EXISTS publ_t;
DROP TYPE IF EXISTS author_t;
DROP TYPE IF EXISTS additional_content_t;
DROP TYPE IF EXISTS month_t;
